### ISSUE TITLE
8.0.1 compatibility

### ISSUE THREAD

**Issue by jystic** [ambiata/jetski#32]
For some reason `libffi.so` is missing on boris under 8.0.1 when it works for 7.10.2:

```
dist/build/test/test: error while loading shared libraries: libffi.so.6: cannot open shared object file: No such file or directory
```

**Comment by erikd-ambiata** [comment]
Ghc 7.10 might have been compiled against an older version of libffi. On my system ghc-7.10 and ghc-8.0 both link against libffi version 6, but I compile mine from source.

**Comment by jystic** [comment]
Fixed! 🍾
